[package]
name = "irontrade"
version = "0.1.8"
edition = "2024"
license = "GPL-3.0-or-later"
description = """
Rust trading client.
"""
repository = "https://github.com/junioraw/irontrade"


[dependencies]
anyhow = "1.0.100"
num-decimal = { version = "0.2.5", default-features = false, features = ["num-v04", "serde"] }
uuid = { version = "1.18.1", features = ["v4"] }
serde = "1.0.228"