[package]
name = "irontrade"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = """
Rust trading client.
"""
repository = "https://github.com/junioraw/irontrade"

[dependencies]
anyhow = "1.0.100"
num-decimal = "0.2.5"
apca = "0.30.0"