[package]
name = "irontrade"
version = "0.1.8"
edition = "2024"
license = "GPL-3.0-or-later"
description = """
Rust trading client.
"""
repository = "https://github.com/junioraw/irontrade"

[features]
default = ["alpaca"]
alpaca = ["dep:apca"] # Whether the Alpaca client is included in the crate

[dependencies]
anyhow = "1.0.100"
num-decimal = { version = "0.2.5", default-features = false, features = ["num-v04", "serde"] }
apca = { git = "https://github.com/junioraw/apca.git", branch = "patch-get_position", optional = true, version = "0.30.0" }
tokio = { version = "1.48.0", features = ["macros", "rt"] }
uuid = { version = "1.18.1", features = ["v4"] }
serde = { version = "1.0.228"}