[package]
name = "irontrade"
version = "0.1.2"
edition = "2024"
license = "GPL-3.0-or-later"
description = """
Rust trading client.
"""
repository = "https://github.com/junioraw/irontrade"

[dependencies]
anyhow = "1.0.100"
num-decimal = { version = "0.2.5", default-features = false, features = ["num-v04", "serde"] }
apca = "0.30.0"
tokio = { version = "1.48.0", features = ["macros"]}