[package]
name = "irontrade"
version = "0.4.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = """
Rust crate with trading interface, driver and simulated environment.
"""
repository = "https://github.com/junioraw/irontrade"

[dependencies]
anyhow = "1.0.100"
num-decimal = { version = "0.2.5", default-features = false, features = ["num-v04"]}
uuid = { version = "1.18.1", features = ["v4"] }
tokio = { version = "1.48.0", features = ["macros", "rt"] }