[package]
name = "irontrade"
version = "0.1.9"
edition = "2024"
license = "GPL-3.0-or-later"
description = """
Rust trading strategies testing.
"""
repository = "https://github.com/junioraw/irontrade"


[dependencies]
anyhow = "1.0.100"
num-decimal = "0.2.5"
uuid = { version = "1.18.1", features = ["v4"] }
tokio = { version = "1.48.0", features = ["macros", "rt"] }